version: '3.8'

services:
  db:
    image: postgres:18
    container_name: SSO_BE
    restart: always
    environment:
      POSTGRES_DB: ssotest
      POSTGRES_USER: ssodev
      POSTGRES_PASSWORD: sso2022ok
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: